import {
	AdminPanelSettings,
	Analytics,
	Anchor,
	DirectionsBoat,
	Feedback,
	Help,
	Link,
	Message,
	MilitaryTech,
	Public,
} from '@mui/icons-material';

import { NavigationConfig } from '../types/navigationTypes';

export const navigationConfig: NavigationConfig = {
	topNav: [
		// {
		// 	title: 'Map',
		// 	href: '/amver-ui/map/',
		// 	disabled: false,
		// 	icon: Public,
		// 	ariaLabel: 'map',
		// 	badgeColor: 'error',
		// 	badgeCount: 0,
		// },
		{
			title: 'Messages',
			href: '/amver-ui/messages/',
			disabled: false,
			icon: Message,
			ariaLabel: 'messages',
			badgeColor: 'error',
			badgeCount: 3,
		},
		// {
		// 	title: 'Notifications',
		// 	href: '/amver-ui/notifications/',
		// 	disabled: false,
		// 	icon: Notifications,
		// 	ariaLabel: 'notifications',
		// },
	],
	leftSideDrawerNav: [
		{
			title: 'Map',
			href: '/amver-ui/map/',
			icon: Public,
			ariaLabel: 'map',
			bottom: false,
			badgeColor: 'error',
			badgeCount: 0,
		},
		{
			title: 'Messages',
			href: '/amver-ui/messages/',
			disabled: false,
			icon: Message,
			ariaLabel: 'messages',
			bottom: false,
			badgeColor: 'error',
			badgeCount: 3,
		},
		{
			title: 'Vessel Information',
			href: '/amver-ui/vessel-information/',
			disabled: false,
			icon: DirectionsBoat,
			ariaLabel: 'vessel information',
			bottom: false,
			badgeColor: 'error',
			badgeCount: 0,
		},
		{
			title: 'Port Information',
			href: '/amver-ui/port-information/',
			disabled: false,
			icon: Anchor,
			ariaLabel: 'port information',
			bottom: false,
			badgeColor: 'warning',
			badgeCount: 1,
		},
		{
			title: 'Awards',
			href: '/amver-ui/awards/',
			disabled: false,
			icon: MilitaryTech,
			ariaLabel: 'awards',
			bottom: false,
			badgeColor: 'success',
			badgeCount: 3,
		},
		{
			title: 'Statistics',
			href: '/amver-ui/statistics/',
			disabled: false,
			icon: Analytics,
			ariaLabel: 'statistics',
			bottom: false,
			badgeColor: 'info',
			badgeCount: 1,
		},
		{
			title: 'Links',
			href: '/amver-ui/links/',
			disabled: false,
			icon: Link,
			ariaLabel: 'links',
			bottom: false,
			badgeColor: 'success',
			badgeCount: 0,
		},
		{
			title: 'Admin',
			href: '/amver-ui/admin/',
			icon: AdminPanelSettings,
			ariaLabel: 'admin',
			bottom: true,
			badgeColor: 'error',
			badgeCount: 0,
		},
		{
			title: 'Help',
			href: '/amver-ui/help/',
			icon: Help,
			ariaLabel: 'help',
			bottom: true,
			badgeColor: 'error',
			badgeCount: 0,
		},
		{
			title: 'Feedback',
			href: '/amver-ui/feedback/',
			icon: Feedback,
			ariaLabel: 'feedback',
			bottom: true,
			badgeColor: 'error',
			badgeCount: 0,
		},
	],
};
